.gitignore, build.gradle, src/main/resources/application-prod.yml, src/main/resources/application.properties, src/main/resources/application.yml
=> yml 파일 생성 및 기본 DB 설정

src/main/java/com/sparta/twotwo/common/exception/ErrorCode.java, src/main/java/com/sparta/twotwo/common/exception/ErrorResponse.java, src/main/java/com/sparta/twotwo/common/exception/GlobalExceptionHandler.java, src/main/java/com/sparta/twotwo/common/exception/TwotwoApplicationException.java, src/main/java/com/sparta/twotwo/store/controller/TestController.java
- ErrorCode Enum Class 추가
- GlobalExceptionHandler 추가
- 임시 ErrorResponse 추가
- 임시 TestController 작성
=> [FEATURE] Add exception handler

src/main/java/com/sparta/twotwo/common/auditing/BaseEntity.java, src/main/java/com/sparta/twotwo/common/config/JpaAuditingConfig.java
- auditing config 추가
- 생성 및 수정 시간, 작성자 및 수정자 필드에 Auditing 기능 적용
=> [FEATURE] BaseEntity 추가

src/main/java/com/sparta/twotwo/enums/OrderType.java, src/main/java/com/sparta/twotwo/order/dto/OrderResponseDto.java, src/main/java/com/sparta/twotwo/order/entity/Order.java
Order Entity  생성
Member, Product Entity가 아직 없어서 연관관계 매핑은 하지 않았습니다.
=> [FEATURE] Order Entity  생성

src/main/java/com/sparta/twotwo/store/controller/StoreController.java, src/main/java/com/sparta/twotwo/store/dto/request/StoreRequest.java, src/main/java/com/sparta/twotwo/store/dto/response/AddressResponse.java, src/main/java/com/sparta/twotwo/store/dto/response/AreaResonse.java, src/main/java/com/sparta/twotwo/store/dto/response/StoreDetailResponse.java, src/main/java/com/sparta/twotwo/store/dto/response/StoreResponse.java, src/main/java/com/sparta/twotwo/store/entity/Address.java, src/main/java/com/sparta/twotwo/store/entity/Area.java, src/main/java/com/sparta/twotwo/store/entity/Store.java, src/main/java/com/sparta/twotwo/store/entity/StoreCategory.java, src/main/java/com/sparta/twotwo/store/repository/StoreCategoryRepository.java, src/main/java/com/sparta/twotwo/store/repository/StoreRepository.java, src/main/java/com/sparta/twotwo/store/service/StoreService.java, src/test/java/com/sparta/twotwo/store/service/StoreServiceTest.java
- AddressResponse 추가
- AreaResponse 추가
- StoreDetailResponse 추가
- StoreReponse 수정
- 가게 전체 조회 API 추가
- 가게 상세 조회 API 추가
- 카테고리별 가게 조회 API 추가
- 가게 전체 조회 Test 코드 추가
=> [Feature] 가게 조회 API

build.gradle
=> [fix]build.gradle

src/main/java/com/sparta/twotwo/auth/config/SecurityConfig.java, src/main/java/com/sparta/twotwo/auth/jwt/JwtUtil.java, src/main/java/com/sparta/twotwo/auth/jwt/filter/JwtAuthorizationFilter.java, src/main/java/com/sparta/twotwo/auth/service/MemberDetailsService.java, src/main/java/com/sparta/twotwo/auth/util/SecurityUtil.java, src/main/java/com/sparta/twotwo/common/auditing/AuditableEntity.java, src/main/java/com/sparta/twotwo/members/controller/MemberController.java, src/main/java/com/sparta/twotwo/members/dto/SignupRequestDto.java, src/main/java/com/sparta/twotwo/members/repository/MemberRepository.java, src/main/java/com/sparta/twotwo/members/service/MemberService.java
deleted_by나 updated_by 에 member_id를 저장하기 위한 로직입니다.
=> feat/securityContext 설정

src/main/java/com/sparta/twotwo/auth/config/SecurityConfig.java, src/main/java/com/sparta/twotwo/product/controller/ProductController.java, src/main/java/com/sparta/twotwo/product/service/ProductService.java
- SecurityConfig에 Product 관련 권한 설정 추가
=> [feature] product 권한 설정

src/main/java/com/sparta/twotwo/ai/controller/AIController.java, src/main/java/com/sparta/twotwo/ai/dto/AIRequestLogResponseDto.java, src/main/java/com/sparta/twotwo/ai/entity/AIRequestLog.java, src/main/java/com/sparta/twotwo/ai/service/AIService.java, src/main/java/com/sparta/twotwo/product/controller/ProductController.java, src/main/java/com/sparta/twotwo/product/dto/ProductUpdateRequestDto.java, src/main/java/com/sparta/twotwo/product/service/ProductService.java
- AI 상품 설명 요청 기능 구현
- ProductService 코드 수정
=> [Feature] AI 설명 요청 기능

src/main/java/com/sparta/twotwo/store/controller/StoreController.java, src/main/java/com/sparta/twotwo/store/dto/request/AddressUpdateRequest.java, src/main/java/com/sparta/twotwo/store/dto/request/StoreCreateRequest.java, src/main/java/com/sparta/twotwo/store/dto/request/StoreUpdateRequest.java, src/main/java/com/sparta/twotwo/store/dto/response/ProductMenuResponse.java, src/main/java/com/sparta/twotwo/store/dto/response/StoreDetailResponse.java, src/main/java/com/sparta/twotwo/store/entity/Store.java, src/main/java/com/sparta/twotwo/store/entity/StoreCategory.java, src/main/java/com/sparta/twotwo/store/repository/AddressRepository.java, src/main/java/com/sparta/twotwo/store/service/AddressService.java, src/main/java/com/sparta/twotwo/store/service/StoreService.java, src/test/java/com/sparta/twotwo/store/service/StoreServiceTest.java
- 가게 등록 API 추가
- 가게 수정 API 추가
- 중복 가게 등록 실패 테스트 추가
- 카테고리별 가게 조회 성공 테스트 추카
- 가게 상세 조회 성공 테스트 추가
- StoreDetailResponse에서 Product 상세 정보까지 반환
- StoreController url 수정
=> [Feature] 가게 등록, 수정 API 및 리팩토링

src/main/java/com/sparta/twotwo/ai/config/GeminiConfig.java, src/main/java/com/sparta/twotwo/ai/service/AIService.java, src/main/java/com/sparta/twotwo/product/dto/ProductListResponseDto.java, src/main/java/com/sparta/twotwo/product/dto/ProductRequestDto.java, src/main/java/com/sparta/twotwo/product/dto/ProductResponseDto.java, src/main/java/com/sparta/twotwo/product/dto/ProductUpdateRequestDto.java, src/main/java/com/sparta/twotwo/product/entity/Product.java, src/main/java/com/sparta/twotwo/product/repository/ProductRepository.java, src/main/java/com/sparta/twotwo/product/service/ProductService.java, src/main/java/com/sparta/twotwo/store/entity/Store.java
- AI 키 불러올 때 에러나는 것 해결
- Store엔티티와 Product 사이에서 타입 에러나서 id를 BINARY(16) 형식으로 저장
- Product 엔티티에 카테고리 필드 필요없다고 판단되어서 삭제
=> [Refactor] product refactor

src/main/java/com/sparta/twotwo/store/dto/response/ProductMenuResponse.java
=> [Refactor] 필드 제거

src/main/java/com/sparta/twotwo/ai/service/AIService.java, src/main/java/com/sparta/twotwo/product/dto/ProductRequestDto.java, src/main/java/com/sparta/twotwo/product/entity/Product.java, src/main/java/com/sparta/twotwo/product/service/ProductService.java
=> [Refactor] ai 요청 로직 수정

src/main/java/com/sparta/twotwo/auth/config/SecurityConfig.java, src/main/java/com/sparta/twotwo/auth/jwt/filter/JwtAuthorizationFilter.java, src/main/java/com/sparta/twotwo/auth/util/AuthorityUtil.java, src/main/java/com/sparta/twotwo/members/controller/MemberController.java, src/main/java/com/sparta/twotwo/members/dto/MemberResponseDto.java, src/main/java/com/sparta/twotwo/members/entity/Member.java, src/main/java/com/sparta/twotwo/members/service/MemberService.java, src/main/java/com/sparta/twotwo/review/service/ReviewService.java, src/test/java/com/sparta/twotwo/store/service/StoreServiceTest.java
owner 권한 설정에 대한 코드입니다. 회원가입 후에 customer 만 가지고 있는 유저에게 manager가 owner 권한을 부여하는 방식으로 설계 되어있습니다. 코드를 작성하는 과정에서 roles의 타입을 List에서 Set으로 변경했기 때문에 List 타입의 roles 부분을 set으로 수정해두었습니다.
=> feat/OWNER 권한 설정

build.gradle, src/main/java/com/sparta/twotwo/common/config/QueryDslConfig.java, src/main/java/com/sparta/twotwo/review/controller/ReviewController.java, src/main/java/com/sparta/twotwo/review/dto/SearchReviewRequestDto.java, src/main/java/com/sparta/twotwo/review/repository/ReviewRepository.java, src/main/java/com/sparta/twotwo/review/repository/ReviewRepositoryCustom.java, src/main/java/com/sparta/twotwo/review/repository/ReviewRepositoryImpl.java, src/main/java/com/sparta/twotwo/review/service/ReviewService.java
queryDsl 설정과 리뷰 조건별 검색, 페이징 기능을 구현했습니다.
=> [Feature] 리뷰 검색 기능

src/main/java/com/sparta/twotwo/TwotwoApplication.java, src/main/java/com/sparta/twotwo/ai/config/GeminiConfig.java, src/main/java/com/sparta/twotwo/ai/controller/AIController.java, src/main/java/com/sparta/twotwo/ai/service/AIService.java, src/main/java/com/sparta/twotwo/auth/config/SecurityConfig.java, src/main/java/com/sparta/twotwo/product/controller/ProductController.java, src/main/java/com/sparta/twotwo/product/dto/ProductUpdateRequestDto.java, src/main/java/com/sparta/twotwo/product/service/ProductService.java
- 상품 생성, 수정 구현 완료
- ai 요청부분 수정
=> [Refactor] product

src/main/java/com/sparta/twotwo/common/config/QueryDslConfig.java
#49 머지 후 수정 영역에 뜨는 파일 다시 머지하겠습니다!
=> 머지 후 반영 안 된 변경사항 커밋

src/main/java/com/sparta/twotwo/common/config/QueryDslConfig.java
QueryDSLConfig -> QueryDslConfig
=> [Fix] QueryDslConfig 클래스명 변경

src/main/java/com/sparta/twotwo/auth/config/SecurityConfig.java, src/main/java/com/sparta/twotwo/auth/util/AuthorityUtil.java, src/main/java/com/sparta/twotwo/common/exception/ErrorCode.java, src/main/java/com/sparta/twotwo/members/controller/MemberController.java, src/main/java/com/sparta/twotwo/members/entity/MemberStatusEnum.java, src/main/java/com/sparta/twotwo/members/repository/MemberRepository.java, src/main/java/com/sparta/twotwo/members/repository/MemberRepositoryCustom.java, src/main/java/com/sparta/twotwo/members/repository/MemberRepositoryImpl.java, src/main/java/com/sparta/twotwo/members/service/MemberService.java
feat/status 별 검색기능 추가
feat/owner 권한 삭제 추가
=> feat/queryDSL 적용

src/main/java/com/sparta/twotwo/review/controller/ReviewController.java, src/main/java/com/sparta/twotwo/review/service/ReviewService.java
- 로그인된 memberId와 주문(Order)의 memberId가 일치하는지 검증하는 로직 구현
- 리뷰 관련 서비스 메서드의 반환 타입 변경
=> [Feature] 주문자와 리뷰 작성자 일치 여부 검증 및 반환 타입 변경

src/main/java/com/sparta/twotwo/common/exception/ErrorCode.java, src/main/java/com/sparta/twotwo/store/entity/Address.java, src/main/java/com/sparta/twotwo/store/entity/Area.java, src/main/java/com/sparta/twotwo/store/entity/Store.java, src/main/java/com/sparta/twotwo/store/entity/StoreCategory.java, src/main/java/com/sparta/twotwo/store/service/StoreService.java
- Store Entity @Where deprecated 되어서 @SqlRestriction으로 변경
=> [REFACTOR] Entity is_deleted 조건 수정

src/test/java/com/sparta/twotwo/order/entity/OrderTest.java
=> [FIX] orderTest
